{{- if .Values.query.enabled -}}
{{- if .Values.serviceAccounts.query.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "thanos.query.labels" . | nindent 4 }}
  name: {{ template "thanos.serviceAccountName.query" . }}
{{ include "thanos.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.query.annotations | indent 4 }}
{{- end }}
{{- end }}
