{{- if and .Values.store.enabled .Values.store.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.store.service.annotations }}
  annotations:
{{ toYaml .Values.store.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "thanos.store.labels" . | nindent 4 }}
{{- if .Values.store.service.labels }}
{{ toYaml .Values.store.service.labels | indent 4 }}
{{- end }}
  name: {{ template "thanos.store.fullname" . }}
{{ include "thanos.namespace" . | indent 2 }}
spec:
{{- if .Values.store.service.clusterIP }}
  clusterIP: {{ .Values.store.service.clusterIP }}
{{- end }}
{{- if .Values.store.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.store.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.store.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.store.service.loadBalancerIP }}
{{- end }}
{{- if .Values.store.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.store.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.store.service.servicePort }}
      protocol: TCP
      targetPort: 9090
    {{- if .Values.store.service.nodePort }}
      nodePort: {{ .Values.store.service.nodePort }}
    {{- end }}
    {{- if .Values.store.service.gRPC.enabled }}
    - name: grpc
      port: {{ .Values.store.service.gRPC.servicePort }}
      protocol: TCP
      targetPort: 10901
    {{- if .Values.store.service.gRPC.nodePort }}
      nodePort: {{ .Values.store.service.gRPC.nodePort }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "thanos.store.matchLabels" . | nindent 4 }}
  type: "{{ .Values.store.service.type }}"
{{- end -}}
