{{- if .Values.store.enabled -}}
{{- if .Values.serviceAccounts.store.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "thanos.store.labels" . | nindent 4 }}
  name: {{ template "thanos.serviceAccountName.store" . }}
{{ include "thanos.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.store.annotations | indent 4 }}
{{- end }}
{{- end }}
